### ISSUE TITLE
R&S ZNA67 support?

### ISSUE THREAD

**Issue by 0xCoto** [mclim9/rssd#4]
Hi, I am trying to interface with the R&S ZNA67. Will [this](https://github.com/mclim9/rssd/blob/master/rssd/examples/VNA/ZVA_S11_A3Wave_Traces.py) script work? My goal is to simply fetch `sNp` data. Can I simply connect my VNA to my machine over LAN and run the script, or do I have to set something up in advance first?

**Comment by mclim9** [comment]
Hello.  Should work for simple functions.  Most of my testing is w/ spectrum analyzers and signal generators.  Code was tested w/ ZVA

**Comment by mclim9** [comment]
Hello.  Should work for simple VNA functions.  Testing was w/ ZBA
